### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [ARM-software/TZ-TRNG#24]
I would like to point out that identifiers like “[`__DX_RNG_H__`](https://github.com/ARM-software/TZ-TRNG/blob/2b487d28e074558afd955546992f4e6b58507e85/shared/hw/include/dx_rng.h#L19-L20 "Update candidate")” and “[`_TZTRNG_H_`](https://github.com/ARM-software/TZ-TRNG/blob/2b487d28e074558afd955546992f4e6b58507e85/host/src/tztrng_lib/include/tztrng.h#L18-L19 "Another update candidate")” [do eventually not fit](https://wiki.sei.cmu.edu/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by xuyong0528** [comment]
These would be kept as they are.
No new release schedule for it.

**Comment by elfring** [comment]
:thought_balloon: Would you like to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by xuyong0528** [comment]
Thanks for the reminder. We'll keep this in mind for future development processes, but for the current software, we plan to maintain it as is.
